#!/bin/bash

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

ps auxw  | grep "console.py" | grep -v grep | grep -v nagios > /dev/null

STATE=$?
if [ "$STATE" = "$STATE_OK" ]; then
    echo "ALARM: OK"
    exit 0
else
    echo "ALARM: Failed"
    exit $STATE_CRITICAL
fi

